// ------------------------------------------------------------
// AI Attribution — per Loren Data AI Use Policy §8.2
// Tool:        Claude Code (Anthropic)
// 2026-05-07: Stub proxy illustrating dotnet-svcutil pattern - Greg Kolinski
// ------------------------------------------------------------

// This file is a REPRESENTATIVE STUB that shows the shape of the generated proxy
// and the types you work with after running dotnet-svcutil against the ECGridOS WSDL.
//
// To regenerate the REAL proxy (replaces this file):
//   dotnet tool install -g dotnet-svcutil
//   dotnet-svcutil https://os.ecgrid.io/v4.1/prod/ECGridOS.asmx?WSDL \
//       --outputDir . \
//       --namespace *,ECGrid.Soap
//
// The generated output will contain strongly-typed async methods for all ~150
// ECGridOS operations.  The binding and endpoint address pattern in Program.cs
// remains exactly the same — only this file changes.

using System.ServiceModel;

namespace ECGrid.Soap;

// ---------------------------------------------------------------------------
// Interface stub — the real IECGridOS is generated from the WSDL
// ---------------------------------------------------------------------------

/// <summary>
/// Representative contract interface for the ECGridOS SOAP service.
/// The actual interface is generated by dotnet-svcutil and will be far more complete.
/// </summary>
[ServiceContract(Namespace = "http://www.ecgridos.net/")]
public interface IECGridOS
{
    /// <summary>Authenticates the user and returns an active session token.</summary>
    [OperationContract(Action = "http://www.ecgridos.net/Login")]
    Task<string> LoginAsync(string userName, string password);

    /// <summary>Returns parcels waiting in the inbound queue for a mailbox.</summary>
    [OperationContract(Action = "http://www.ecgridos.net/ParcelInBox")]
    Task<ParcelIDInfo[]> ParcelInBoxAsync(string sessionID, int networkID, int mailboxID);

    /// <summary>Downloads the raw EDI content of a single parcel.</summary>
    [OperationContract(Action = "http://www.ecgridos.net/ParcelDownload")]
    Task<byte[]> ParcelDownloadAsync(string sessionID, long parcelID);

    /// <summary>Confirms successful receipt; ECGridOS will not re-deliver after this call.</summary>
    [OperationContract(Action = "http://www.ecgridos.net/ParcelDownloadConfirm")]
    Task<bool> ParcelDownloadConfirmAsync(string sessionID, long parcelID);

    /// <summary>Terminates the active session.</summary>
    [OperationContract(Action = "http://www.ecgridos.net/Logout")]
    Task<bool> LogoutAsync(string sessionID);
}

// ---------------------------------------------------------------------------
// Client stub — replace with generated ECGridOSClient after running svcutil
// ---------------------------------------------------------------------------

/// <summary>
/// Stub WCF client class.  After running dotnet-svcutil the generated version will
/// inherit from <c>ClientBase&lt;IECGridOS&gt;</c> and implement all interface members.
/// </summary>
public partial class ECGridOSClient : ClientBase<IECGridOS>, IECGridOS
{
    /// <summary>
    /// Constructs the client with a pre-configured binding and remote endpoint.
    /// This constructor signature is preserved by dotnet-svcutil.
    /// </summary>
    /// <param name="binding">Transport binding (use <c>BasicHttpsBinding</c> for ECGridOS).</param>
    /// <param name="remoteAddress">Service endpoint address.</param>
    public ECGridOSClient(System.ServiceModel.Channels.Binding binding,
                          EndpointAddress remoteAddress)
        : base(binding, remoteAddress) { }

    /// <inheritdoc/>
    public Task<string> LoginAsync(string userName, string password)
        => throw new NotImplementedException(
            "Replace this file with the output of: " +
            "dotnet-svcutil https://os.ecgrid.io/v4.1/prod/ECGridOS.asmx?WSDL");

    /// <inheritdoc/>
    public Task<ParcelIDInfo[]> ParcelInBoxAsync(string sessionID, int networkID, int mailboxID)
        => throw new NotImplementedException("Replace with generated proxy.");

    /// <inheritdoc/>
    public Task<byte[]> ParcelDownloadAsync(string sessionID, long parcelID)
        => throw new NotImplementedException("Replace with generated proxy.");

    /// <inheritdoc/>
    public Task<bool> ParcelDownloadConfirmAsync(string sessionID, long parcelID)
        => throw new NotImplementedException("Replace with generated proxy.");

    /// <inheritdoc/>
    public Task<bool> LogoutAsync(string sessionID)
        => throw new NotImplementedException("Replace with generated proxy.");
}

// ---------------------------------------------------------------------------
// Data transfer object stubs — generated svcutil output will replace these
// ---------------------------------------------------------------------------

/// <summary>
/// Represents a single parcel in the ECGridOS inbound queue.
/// The actual generated type will include all fields from the WSDL schema.
/// </summary>
public record ParcelIDInfo(
    /// <summary>Unique numeric identifier for the parcel.</summary>
    long ParcelID,

    /// <summary>Original file name as submitted by the sending trading partner.</summary>
    string FileName,

    /// <summary>Size of the parcel in bytes.</summary>
    long FileSize,

    /// <summary>Timestamp when the parcel arrived in the ECGrid network (UTC).</summary>
    DateTime MailbagDate,

    /// <summary>Sender's ECGrid network ID.</summary>
    int SenderNetworkID,

    /// <summary>Sender's ECGrid mailbox ID.</summary>
    int SenderMailboxID
);
