// AI Attribution — Loren Data AI Use Policy §8.2
// Tool:        Claude Code (Anthropic)
// 2026-05-07: Initial ECGrid Developer Documentation Portal sidebars - Greg Kolinski
// 2026-05-08: Merge guides into getting-started; remove separate guides autogeneration - Greg Kolinski

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // 1. Getting Started (includes all guides — merged into one section)
  gettingStartedSidebar: [
    {
      type: "autogenerated",
      dirName: "getting-started",
    },
  ],

  // 3. REST API (v2.6 — Active)
  restApiSidebar: [
    {
      type: "autogenerated",
      dirName: "rest-api",
    },
  ],

  // 4. SOAP API (v4.1 — Legacy)
  soapApiSidebar: [
    {
      type: "autogenerated",
      dirName: "soap-api",
    },
  ],

  // 5. Common Operations
  commonOpsSidebar: [
    {
      type: "autogenerated",
      dirName: "common-operations",
    },
  ],

  // 6. Appendix
  appendixSidebar: [
    {
      type: "autogenerated",
      dirName: "appendix",
    },
  ],

  // 7. Code Samples
  samplesSidebar: [
    {
      type: "autogenerated",
      dirName: "code-samples",
    },
  ],

  // 8. Changelog
  changelogSidebar: [
    {
      type: "autogenerated",
      dirName: "changelog",
    },
  ],
};

export default sidebars;
